In [1]:
import csv

In [4]:
import numpy as np

In [6]:
order = []
name = []
height = []
index = 0
with open( 'president_heights.csv', 'r' ) as f:
    reader = csv.reader( f )
    for row in reader:
        if index != 0:
            order.append( row[0] )
            name.append( row[1] )
            height.append( int(row[2]) )
        index += 1
print( order )
print( name )
print( height )

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '23', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44']
['George Washington', 'John Adams', 'Thomas Jefferson', 'James Madison', 'James Monroe', 'John Quincy Adams', 'Andrew Jackson', 'Martin Van Buren', 'William Henry Harrison', 'John Tyler', 'James K. Polk', 'Zachary Taylor', 'Millard Fillmore', 'Franklin Pierce', 'James Buchanan', 'Abraham Lincoln', 'Andrew Johnson', 'Ulysses S. Grant', 'Rutherford B. Hayes', 'James A. Garfield', 'Chester A. Arthur', 'Benjamin Harrison', 'William McKinley', 'Theodore Roosevelt', 'William Howard Taft', 'Woodrow Wilson', 'Warren G. Harding', 'Calvin Coolidge', 'Herbert Hoover', 'Franklin D. Roosevelt', 'Harry S. Truman', 'Dwight D. Eisenhower', 'John F. Kennedy', 'Lyndon B. Johnson', 'Richard Nixon', 'Gerald Ford', 'Jimmy Carter', 'Ronald Reagan', 'George H. W. Bush'

In [9]:
order = np.array( order )
name = np.array( name )
height = np.array( height )

In [11]:
np.mean( height )

179.73809523809524

In [17]:
name[ height == np.max(height) ]

array(['Abraham Lincoln', 'Lyndon B. Johnson'], dtype='<U22')

In [13]:
name[ height == np.min(height) ]

array(['James Madison'], dtype='<U22')

In [18]:
name[ height <= np.mean( height ) ]

array(['John Adams', 'James Madison', 'John Quincy Adams',
       'Martin Van Buren', 'William Henry Harrison', 'James K. Polk',
       'Zachary Taylor', 'Millard Fillmore', 'Franklin Pierce',
       'Andrew Johnson', 'Ulysses S. Grant', 'Rutherford B. Hayes',
       'Benjamin Harrison', 'William McKinley', 'Theodore Roosevelt',
       'Calvin Coolidge', 'Harry S. Truman', 'Dwight D. Eisenhower',
       'Jimmy Carter'], dtype='<U22')

In [19]:
name[ height >= np.mean( height ) ]

array(['George Washington', 'Thomas Jefferson', 'James Monroe',
       'Andrew Jackson', 'John Tyler', 'James Buchanan',
       'Abraham Lincoln', 'James A. Garfield', 'Chester A. Arthur',
       'William Howard Taft', 'Woodrow Wilson', 'Warren G. Harding',
       'Herbert Hoover', 'Franklin D. Roosevelt', 'John F. Kennedy',
       'Lyndon B. Johnson', 'Richard Nixon', 'Gerald Ford',
       'Ronald Reagan', 'George H. W. Bush', 'Bill Clinton',
       'George W. Bush', 'Barack Obama'], dtype='<U22')

In [89]:
date = []
prcp = []
index = 0
with open( 'Seattle2014.csv', 'r' ) as f:
    reader = csv.reader( f )
    for row in reader:
        if index != 0:
            date.append( row[2][4::] )
            prcp.append( int(row[3]) )
        index += 1
print( date )
print()
print( prcp )

['0101', '0102', '0103', '0104', '0105', '0106', '0107', '0108', '0109', '0110', '0111', '0112', '0113', '0114', '0115', '0116', '0117', '0118', '0119', '0120', '0121', '0122', '0123', '0124', '0125', '0126', '0127', '0128', '0129', '0130', '0131', '0201', '0202', '0203', '0204', '0205', '0206', '0207', '0208', '0209', '0210', '0211', '0212', '0213', '0214', '0215', '0216', '0217', '0218', '0219', '0220', '0221', '0222', '0223', '0224', '0225', '0226', '0227', '0228', '0301', '0302', '0303', '0304', '0305', '0306', '0307', '0308', '0309', '0310', '0311', '0312', '0313', '0314', '0315', '0316', '0317', '0318', '0319', '0320', '0321', '0322', '0323', '0324', '0325', '0326', '0327', '0328', '0329', '0330', '0331', '0401', '0402', '0403', '0404', '0405', '0406', '0407', '0408', '0409', '0410', '0411', '0412', '0413', '0414', '0415', '0416', '0417', '0418', '0419', '0420', '0421', '0422', '0423', '0424', '0425', '0426', '0427', '0428', '0429', '0430', '0501', '0502', '0503', '0504', '0505',

In [90]:
date = np.array( date )
prcp = np.array( prcp )

In [91]:
np.mean( prcp )

33.775342465753425

In [92]:
date[ prcp >= np.mean(prcp)]

array(['0102', '0107', '0108', '0109', '0110', '0111', '0128', '0129',
       '0208', '0210', '0211', '0212', '0214', '0215', '0216', '0217',
       '0218', '0223', '0224', '0302', '0303', '0304', '0305', '0308',
       '0309', '0310', '0314', '0315', '0316', '0325', '0326', '0328',
       '0329', '0405', '0408', '0416', '0417', '0419', '0421', '0422',
       '0423', '0424', '0427', '0503', '0504', '0505', '0508', '0523',
       '0525', '0613', '0616', '0723', '0812', '0813', '0830', '0923',
       '0924', '0925', '0926', '1011', '1013', '1014', '1015', '1018',
       '1020', '1022', '1023', '1024', '1025', '1028', '1030', '1031',
       '1103', '1104', '1105', '1106', '1109', '1120', '1121', '1123',
       '1125', '1128', '1129', '1206', '1208', '1209', '1210', '1211',
       '1218', '1220', '1223', '1224', '1228'], dtype='<U4')

In [93]:
date[ prcp <= np.mean(prcp)]

array(['0101', '0103', '0104', '0105', '0106', '0112', '0113', '0114',
       '0115', '0116', '0117', '0118', '0119', '0120', '0121', '0122',
       '0123', '0124', '0125', '0126', '0127', '0130', '0131', '0201',
       '0202', '0203', '0204', '0205', '0206', '0207', '0209', '0213',
       '0219', '0220', '0221', '0222', '0225', '0226', '0227', '0228',
       '0301', '0306', '0307', '0311', '0312', '0313', '0317', '0318',
       '0319', '0320', '0321', '0322', '0323', '0324', '0327', '0330',
       '0331', '0401', '0402', '0403', '0404', '0406', '0407', '0409',
       '0410', '0411', '0412', '0413', '0414', '0415', '0418', '0420',
       '0425', '0426', '0428', '0429', '0430', '0501', '0502', '0506',
       '0507', '0509', '0510', '0511', '0512', '0513', '0514', '0515',
       '0516', '0517', '0518', '0519', '0520', '0521', '0522', '0524',
       '0526', '0527', '0528', '0529', '0530', '0531', '0601', '0602',
       '0603', '0604', '0605', '0606', '0607', '0608', '0609', '0610',
      

In [26]:
np.max( prcp ), np.min( prcp )

(467, 0)

In [27]:
np.sum( prcp == 0 )

215

In [28]:
np.sum( prcp != 0 )

150

In [30]:
date[ prcp == np.max( prcp ) ]

array(['0305'], dtype='<U4')

In [31]:
date[ prcp == np.min( prcp ) ]

array(['0101', '0104', '0105', '0113', '0114', '0115', '0116', '0117',
       '0118', '0119', '0120', '0121', '0123', '0124', '0125', '0126',
       '0127', '0130', '0202', '0203', '0204', '0205', '0206', '0207',
       '0226', '0227', '0228', '0307', '0311', '0312', '0318', '0320',
       '0321', '0322', '0323', '0324', '0330', '0331', '0401', '0402',
       '0404', '0406', '0407', '0409', '0410', '0411', '0412', '0413',
       '0414', '0418', '0420', '0425', '0428', '0429', '0430', '0501',
       '0502', '0506', '0507', '0511', '0512', '0513', '0514', '0515',
       '0516', '0517', '0518', '0519', '0520', '0521', '0522', '0524',
       '0526', '0527', '0528', '0529', '0530', '0531', '0601', '0602',
       '0603', '0604', '0605', '0606', '0607', '0608', '0609', '0610',
       '0611', '0614', '0618', '0621', '0622', '0623', '0624', '0625',
       '0626', '0629', '0630', '0701', '0702', '0703', '0704', '0705',
       '0706', '0707', '0708', '0709', '0710', '0711', '0712', '0713',
      

In [43]:
area = []
week = []
date = []
name = []
weather = []
m10 = []
m20 = []
m30 = []
m40 = []
m50 = []
f10 = []
f20 = []
f30 = []
f40 = []
f50 = []
index = 0
with open( 'korea_floating_population_data.csv', 'r' ) as f:
    reader = csv.reader( f )
    for row in reader:
        if index != 0:
            area.append( row[ 1 ] )
            week.append( row[ 2 ] )
            date.append( row[ 3 ] )
            name.append( row[ 7 ] )
            weather.append( row[ 8 ] )
            m10.append( int(row[ 9 ]) )
            m20.append( int(row[ 10 ]) )
            m30.append( int(row[ 11 ]) )
            m40.append( int(row[ 12 ]) )
            m50.append( int(row[ 13 ]) )
            f10.append( int(row[ 14 ]) )
            f20.append( int(row[ 15 ]) )
            f30.append( int(row[ 16 ]) )
            f40.append( int(row[ 17 ]) )
            f50.append( int(row[ 18 ]) )
            
        index += 1

In [44]:
area = np.array( area )
week = np.array( week )
date = np.array( date )
name = np.array( name )
weather = np.array( weather )
pop = np.array( [ m10, m20, m30, m40, m50, f10, f20, f30, f40, f50 ] )

In [45]:
pop

array([[ 2, 19, 13, ..., 25, 12, 15],
       [24, 44, 33, ..., 13, 15, 20],
       [68, 28, 34, ..., 29, 35, 32],
       ...,
       [64, 49, 29, ..., 37, 31, 29],
       [44, 43, 28, ..., 19, 25, 31],
       [26, 18, 12, ..., 45, 37, 43]])

In [51]:
pop_sum = np.add.reduce( pop )

In [50]:
weather == '맑음'

array([ True,  True, False, ...,  True,  True,  True])

In [55]:
np.sum( pop_sum[ weather == '맑음' ] )

9903515

In [56]:
np.sum( pop_sum[weather == '흐림' ] )

2848118

In [57]:
np.sum( pop_sum[weather == '비' ] )

1300890

In [58]:
np.max( pop_sum )

16951

In [63]:
name[ np.max( pop_sum ) ], area[ np.max( pop_sum ) ], date[ np.max( pop_sum ) ], week[ np.max( pop_sum ) ], weather[ np.max( pop_sum ) ]

('경상북도 구미시 인동동', '롯데리아앞', '2010-10-26', '주중', '맑음')

In [64]:
name[ np.min( pop_sum ) ], area[ np.min( pop_sum ) ], date[ np.min( pop_sum ) ], week[ np.min( pop_sum ) ], weather[ np.min( pop_sum ) ]

('대전광역시 서구 월평동', '신촌네거리 계룡건설 사옥 농협 앞', '2010-06-21', '주중', '맑음')

In [87]:
pop.max( axis = 1 )[ : , np.newaxis ]

array([[ 1520],
       [ 2700],
       [ 2730],
       [ 1662],
       [ 1700],
       [ 2792],
       [ 4212],
       [ 2884],
       [11218],
       [ 5717]])